apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javaapp
  namespace: argocd # Namespace where the Argo CD Application resource lives
spec:
  project: default # The Argo CD Project this application belongs to
  source:
    repoURL: https://github.com/iam-dasari/github-actions.git
    targetRevision: main
    path: .
    helm:
      releaseName: cicd
      valueFiles:
      - helm/values.yaml
  destination:
    server: https://kubernetes.default.svc # The API server URL of the target Kubernetes cluster
    namespace: argocd # The namespace in the target cluster where the application will be deployed
  syncPolicy:
    automated: # Enable automated synchronization
      prune: true # Delete resources that are no longer in Git
      selfHeal: true # Revert changes made manually in the cluster to match Git
    syncOptions:
      - CreateNamespace=true # Automatically create the target namespace if it doesn't exist